### ISSUE TITLE
Not sure where my level was published

### ISSUE THREAD

**Issue by songproducer** [lentsius-bark/zame-zeroframe-godot#2]
I have ZeroNet running but not sure where my level is published.

**Comment by lentsius-bark** [comment]
The publishing to ZeroNet is a feature we're working on right now. It's not in the build yet. The readme is not clear on that. I will change it accordingly right away.
In the future Zame itself will have an in-game level browser which lets you explore all of the published user levels.
If you have any feedback about Zame so far, we'd love to hear it!
